<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>" >
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Currency') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger currency-tooltip-bottom" aria-describedby="tooltip-5" id="switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <?php if($block->escapeHtml($currentCurrencyCode == 'USD')):?>
                <span><i class="fa fa-usd" aria-hidden="true"></i></span>
                <?php elseif($block->escapeHtml($currentCurrencyCode == 'EUR')):?>
                <span><i class="fa fa-eur" aria-hidden="true"></i></span>
                <?php else:?>
                <span><i class="fa fa-gbp" aria-hidden="true"></i></span>
                <?php endif;?>
            </strong>
            <span class="tooltip-content" id="tooltip-5" role="tooltip"><?php echo __('Currency');?></span>
        </div>

        <ul class="dropdown switcher-dropdown">
            <li class="currency-label"><?php echo __('Choose Your Currency:')?></li>
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */
						switch ($_code) {
						    case "USD":
						        echo "$";
						        break;
						    case "EUR":
						        echo "€";
						        break;
						    case "GBP":
						        echo "£";
						        break;
						    default:
						        echo $_code ?> - <?php echo $_name;
						}
                        ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
<script>
    //add hover effect on minicart after remove magento default dropdown
    requirejs(['jquery'],function(jQuery){
        jQuery('.switcher-options').hover(function(){
            jQuery('.switcher-options').toggleClass('active');
        });
    });
</script>
