<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php /* @escapeNotVerified */ echo __('There are no items in your shopping basket.') ?></p>
    <a href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()); ?>" class="btn-empty"><?php
    echo __('Continue Shopping');?></a>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
</div>
