<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom_menu_responsive')->toHtml();?>
</nav>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom_top_link')->toHtml();?>
