<?php
/**
 * Solwin Infotech
 * Solwin Featured Product Extension
 *
 * @category   Solwin
 * @package    Solwin_FeaturedPro
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Solwin\FeaturedPro\Helper\Data');
$enableModule = $helper->getConfigValue('featuredpro_settings/featured_products/enable');
if ($enableModule) {

    $block_title = $this->getData('widget_title');

    $_productCollection = $block->getProductCollection()->addAttributeToSelect('*')->addAttributeToFilter('type_id', array('eq' => 'simple'))->setCurPage(1)->setPageSize(4);;
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    ?>

    <?php if ($_productCollection->count()): ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        $pos = $block->getPositioned();
        $position = '';
        if ($pos != null) {
            $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
                . 'top:' . $block->getVar("{$image}:height") . 'px;"';
        }
        ?>
        <?php if($_productCollection->count()){?>
            <div class="pad-main-bottom wrapper grid products-grid">
                <div >
                    <div class="block-title-main">
                        <h2><?php echo __('New Products'); ?></h2>
                        <div class="title-border"></div>
                    </div>
                    <?php $iterator = 1; ?>
                    <ol class="products list items product-items featuredproduct">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($_productCollection as $_product):?>
                            <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php // Product Image     ?>

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <div class="top-label-wrapper">
                                            <?php
                                            $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                ->init($_product, 'product_page_image_large')
                                                ->constrainOnly(FALSE)
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize(270, 371)
                                                ->getUrl();
                                            ?>
                                            <?php //check product new?>
                                            <?php $newsFromDate = $_product->getNewsFromDate();
                                            $newsToDate   = $_product->getNewsToDate();
                                            $isNew ='';
                                            if (!$newsFromDate && !$newsToDate) :
                                                $isNew = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isNew = $resolver->isScopeDateInInterval(
                                                    $_product->getStore(),
                                                    $newsFromDate,
                                                    $newsToDate
                                                );
                                            endif; ?>
                                            <?php if($isNew):?>
                                                <span class="new-label"><?php echo __('New');?></span>
                                            <?php endif;?>

                                            <?php //check product special price?>
                                            <?php
                                            $specialPriceFromDate = $_product->getSpecialFromDate();
                                            $specialPriceToDate = $_product->getSpecialToDate();
                                            $isSpecial = '';
                                            if (!$specialPriceFromDate && !$specialPriceToDate) :
                                                $isSpecial = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isSpecial = $resolver->isScopeDateInInterval(
                                                    $_product->getStore(),
                                                    $specialPriceFromDate,
                                                    $specialPriceToDate
                                                );
                                            endif;?>
                                            <?php if($isSpecial):?>
                                                <span class="sale-label"><?php echo __('Sale');?></span>
                                            <?php endif;?>
                                        </div>
                                        <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <div class="view-product-tab"><?php echo __('View Product');?></div>
                                        </a>
                                        <div class="featured-image">
                                            <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                            <div class="overlay-featured"></div>
                                        </div>
                                        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

                                        $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

                                        $addToCartUrl =  $listBlock->getAddToCartUrl($_product);?>

                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form  action="<?php echo $addToCartUrl; ?>" method="post">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="Add to Cart"
                                                        class="actions-primary">
                                                    <i class="material-icons">add</i>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <di class="stock available"><span><?php echo __('In stock') ?></span></di>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                    </span>
                                </span>


                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php echo $_product->getProductUrl() ?>">
                                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <div class="description"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');?></div>
                                    <?php echo $block->getProductPrice($_product) ?>

                                </div>
                            </div>
                            <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        <?php }?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>
        <?php endif; ?>
    <?php endif; ?>

    <?php
}?>