<?php
/**
 * custom cart top
 */
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();?>
<div class="cart-top-wrapper">
    <div class="cart-top-label">
        <i class="material-icons">shopping_basket</i>
        <span class="basket-text"><?php echo __('Your Shopping Basket');?></span>
    </div>
    <div class="cart-checkout-button">
        <a class="action primary checkout" href="<?php echo $baseUrl.'checkout'?>">
            <span class="checkout-text"><?php echo __('Continue to Checkout');?></span>
        </a>
    </div>
</div>