<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$list = $objectManager->get('Magento\Catalog\Block\Product\ListProduct');
?>
    <div class="cart item">
        <div class="item-info">
            <div data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                       title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                <?php else:?>
                    <span class="product-item-photo">
                <?php endif;?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()):?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>

            </div>
            <div class="product-data-wrap">
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()):?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                            <?php echo $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                        <span class="product-code">
                            <?php echo __('Product Code').':'.$block->escapeHtml($_item->getSku());?>
                        </span>
                    </strong>
                    <?php //var_dump($block->getItem()->getData())?>
                    <?php if ($_options = $block->getOptionList()):?>
<!--                        <dl class="tem-options">-->
<!--                            --><?php //foreach ($_options as $_option) : ?>
<!--                                --><?php //$_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
<!--                                <dt>--><?php //echo $block->escapeHtml($_option['label']) ?><!--</dt>-->
<!--                                <dd>-->
<!--                                    --><?php //if (isset($_formatedOptionValue['full_view'])): ?>
<!--                                        --><?php ///* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
<!--                                    --><?php //else: ?>
<!--                                        --><?php ///* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
<!--                                    --><?php //endif; ?>
<!--                                </dd>-->
<!--                            --><?php //endforeach; ?>
<!--                        </dl>-->

                    <?php endif;?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
            <div class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
                <div class="actions-toolbar">
                    <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
                </div>
                <div class="field qty">
                    <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                        <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                    </label>
                    <div class="control qty">
                        <button onclick="decreaser('cart-<?php echo $_item->getId() ?>-qty')" type="button" class="decrease"><i class="material-icons">remove_circle_outline</i></button>
                        <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                               name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                               data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                               value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                               type="number"
                               size="4"
                               title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                               class="input-text qty"
                               maxlength="12"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                        <button onclick="increaser('cart-<?php echo $_item->getId() ?>-qty')" type="button" class="increase"><i class="material-icons">add_circle</i></button>

                    </div>
                </div>
            </div>
            <?php if ($canApplyMsrp): ?>
                <div class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                    <span class="pricing msrp">
                        <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                        <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                            <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                        </a>
                    </span>
                </div>
            <?php else: ?>
                <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                    <?php echo $block->getUnitPriceHtml($_item); ?>
                </td>
            <?php endif; ?>


            <div class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                    <?php echo $block->getRowTotalHtml($_item); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<div class="cart-section-wrapper">
    <?php $relatedProducts = $product->getRelatedProductCollection()
        ->addFinalPrice()
        ->addUrlRewrite()
        ->addAttributeToSelect('name')
        ->addAttributeToSelect('short_description')
        ->addAttributeToSelect('image')
        ->setPageSize(3)
        ->setCurPage(1);

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $baseUrl =$storeManager->getStore()->getBaseUrl().'pub/static/frontend/E3donline/default/en_US/Magento_Catalog/images/product/placeholder/image.jpg';
    if (count($relatedProducts)) {?>
        <div class="toggle-wrapper"><div onclick="toggleCart(<?php echo $_item->getId()?>)" class="cart-toggle">
                <span class="open-toggle open-toggle-cart-<?php echo $_item->getId()?>">
                    <?php echo __('Open Compatible Products')?>
                </span>
                <span class="close-toggle close-toggle-cart-<?php echo $_item->getId()?>" style="display:none">
                    <?php echo __('Close Compatible Products')?>
                </span>
            </div>
        </div>
        <div class="cart-related-section checkout-cart-related-<?php echo $_item->getId()?>" style="display:none">
            <div class="cart-related-wrapper">
                <?php  foreach ($relatedProducts as $relatedProduct) {?>
                    <div class="item product product-item">
                        <a href="<?php echo $relatedProduct->getProductUrl()?>">
                            <div class="product-item-info">
                            <span class="product-image-container">
                                <span class="product-image-wrapper">
                                    <div class="featured-image">
                                        <img src="<?php
                                        if($relatedProduct->getImage()){
                                            echo $mediaUrl.'catalog/product'.$relatedProduct->getImage();
                                        }else{
                                            echo $baseUrl;
                                        } ?>"/>
                                    </div>
                                </span>
                            </span>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><?php echo $relatedProduct->getName()?></strong>
                                <div class="description"><?php echo $relatedProduct->getShortDescription();?></div>
                                <div class="price-box price-final_price"><?php echo $list->getProductPrice($relatedProduct);?></div>
                            </div>
                        </div>
                        </a>
                    </div>
                <?php }?>
            </div>
        </div>
    <?php   } ?>
</div>
<script type="text/javascript">

        function increaser(id){
            qty = parseInt(document.getElementById(id).value);
            qty =qty+1;
            document.getElementById(id).value = qty;
        }

        function decreaser(id){
            qty = parseInt(document.getElementById(id).value);
            if(qty>0){
                qty =qty-1;
            }
            document.getElementById(id).value = qty;
        }


        function toggleCart(id){
        requirejs(['jquery'],function($){
            $('.checkout-cart-related-'+id).slideToggle(200);
            $('.open-toggle-cart-'+id).toggle();
            $('.close-toggle-cart-'+id).toggle();
            });
        }

</script>