<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('Suggested Products');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('Suggested - Products');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
<!--    <div class="block-title title">-->
<!--        <strong id="block---><?php ///* @escapeNotVerified */ echo $class?><!---heading" role="heading" aria-level="2">--><?php ///* @escapeNotVerified */ echo $title; ?><!--</strong>-->
<!--    </div>-->
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
<!--        <div class="block-actions">-->
<!--            --><?php ///* @escapeNotVerified */ //echo __('Check items to add to the cart or') ?>
<!--            <button type="button" class="action select" role="select-all"><span>--><?php ///* @escapeNotVerified */ //echo __('select all') ?><!--</span></button>-->
<!--        </div>-->
        <?php endif; ?>

        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <strong>
                <span class="related-title">
                    <?php echo __('Related Products');?>
                </span>
            </strong>
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                    <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <div class="top-label-wrapper">
                                            <?php
                                            $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                ->init($_item, 'product_page_image_large')
                                                ->constrainOnly(FALSE)
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize(270, 371)
                                                ->getUrl();
                                            ?>
                                            <?php //check product new?>
                                            <?php $newsFromDate = $_item->getNewsFromDate();
                                            $newsToDate   = $_item->getNewsToDate();
                                            $isNew ='';
                                            if (!$newsFromDate && !$newsToDate) :
                                                $isNew = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isNew = $resolver->isScopeDateInInterval(
                                                    $_item->getStore(),
                                                    $newsFromDate,
                                                    $newsToDate
                                                );
                                            endif; ?>
                                            <?php if($isNew):?>
                                                <span class="new-label"><?php echo __('New');?></span>
                                            <?php endif;?>

                                            <?php //check product special price?>
                                            <?php
                                            $specialPriceFromDate = $_item->getSpecialFromDate();
                                            $specialPriceToDate = $_item->getSpecialToDate();
                                            $isSpecial = '';
                                            if (!$specialPriceFromDate && !$specialPriceToDate) :
                                                $isSpecial = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isSpecial = $resolver->isScopeDateInInterval(
                                                    $_item->getStore(),
                                                    $specialPriceFromDate,
                                                    $specialPriceToDate
                                                );
                                            endif;?>
                                            <?php if($isSpecial):?>
                                                <span class="sale-label"><?php echo __('Sale');?></span>
                                            <?php endif;?>
                                        </div>
                                        <a href="<?php echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <div class="view-product-tab"><?php echo __('View Product');?></div>
                                        </a>
                                        <div class="featured-image">
                                            <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                            <div class="overlay-featured"></div>
                                        </div>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <a href="<?php echo $_item->getProductUrl() ?>" class="product-page-link">
                                                    <i class="material-icons">add</i>
                                                </a>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </span>
                                </span>



                    <div class="product details product-item-details">
                        <?php
                        $_itemNameStripped = $block->stripTags($_item->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo $_item->getProductUrl() ?>">
                                <?php echo $_item->getName(); ?>
                            </a>
                        </strong>
                        <div class="description"><?php echo  $_item->getShortDescription(); ?></div>
                        <?php echo $block->getProductPrice($_item) ?>

                    </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
