<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$registryInstance = $objectManager->get('\Magento\Framework\Registry');
$currentCategory = $registryInstance->registry('current_category');
$subcategories='';
$currentCategoryLevel=0;
if(is_object($currentCategory)) {
    $currentCategoryLevel = $currentCategory->getLevel();

    $subcategories = $currentCategory->getChildrenCategories();
}

if(is_object($currentCategory)) {
    $categoryDescription = $currentCategory->getDescription();
    $categoryImage = $currentCategory->getImageUrl();
    if ($categoryImage == '') {
        $categoryImage = $this->getViewFileUrl('images/category.jpg');
    }
}
?>
<?php if (!$_productCollection->count()): ?>
    <?php if(($currentCategoryLevel == 2)&&($subcategories->count()>0)){ ?>

        <div class="products wrapper">

            <?php foreach ($subcategories as $subcategory) {
                $categoryInstance = $objectManager->get('\Magento\Catalog\Model\Category');
                $subCatImage = $categoryInstance->load($subcategory->getId())->getImageUrl();

                if ($subCatImage == '') {
                    $subCatImage = $this->getViewFileUrl('images/category.jpg');
                }?><a href="<?php echo $subcategory->getUrl(); ?>">
                <img class="subcategory-image" src="<?php echo $subCatImage; ?>"/>

                <strong class="category name ">

                    <?php echo $subcategory->getName(); ?>

                </strong>
                </a>
            <?php } ?>
            <script type="text/javascript">

                requirejs(['jquery'],function(jQuery){
                    jQuery('.sidebar').hide();
                    jQuery('.main').addClass('full-width');
                    jQuery('.category-info').click(function(){
                        jQuery(this).addClass('active');
                        jQuery('.browse-tab').removeClass('active');
                        jQuery('.category-information-section').show();
                        jQuery('.products-grid, .sidebar-main').hide();
                        jQuery('.main').addClass('full-width');
                    });

                    jQuery('.browse-tab').click(function(){
                        jQuery(this).addClass('active');
                        jQuery('.category-info').removeClass('active');
                        jQuery('.category-information-section').hide();
                        jQuery('.products-grid, .sidebar-main').show();
                        jQuery('.sidebar').hide();

                    });
                })
            </script>


        </div>
    <?php   }else{?>
        <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php }?>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php if(is_object($currentCategory)) {?>
        <div class="category-information-section" style="display:none">
            <img class="category-image" src="<?php echo $categoryImage; ?>"/>
            <div class="category-content">
                <div class="category-heading"><?php echo __('Category Information')?></div>
                <?php if($categoryDescription!=''){
                    echo $categoryDescription;
                }
                ?></div>
        </div>
    <?php }?>

    <?php if(($currentCategoryLevel == 2)&&($subcategories->count()>0)){ ?>

        <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">

            <?php foreach ($subcategories as $subcategory) {
                $categoryInstance = $objectManager->get('\Magento\Catalog\Model\Category');
                $subCatImage = $categoryInstance->load($subcategory->getId())->getImageUrl();

                if ($subCatImage == '') {
                    $subCatImage = $this->getViewFileUrl('images/category.jpg');
                }?><a href="<?php echo $subcategory->getUrl(); ?>">
                <img class="subcategory-image" src="<?php echo $subCatImage; ?>"/>

                <strong class="category name ">

                    <?php echo $subcategory->getName(); ?>

                </strong>
                </a>
            <?php } ?>
            <script type="text/javascript">

                requirejs(['jquery'],function(jQuery){
                    jQuery('.sidebar').hide();
                    jQuery('.main').addClass('full-width');
                    jQuery('.category-info').click(function(){
                        jQuery(this).addClass('active');
                        jQuery('.browse-tab').removeClass('active');
                        jQuery('.category-information-section').show();
                        jQuery('.products-grid, .sidebar-main').hide();
                        jQuery('.main').addClass('full-width');
                    });

                    jQuery('.browse-tab').click(function(){

                        jQuery(this).addClass('active');
                        jQuery('.category-info').removeClass('active');
                        jQuery('.category-information-section').hide();
                        jQuery('.products-grid, .sidebar-main').show();
                        jQuery('.sidebar').hide();

                    });
                })
            </script>


        </div>
    <?php   }else{ ?>
        <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php // Product Image     ?>

                        <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <div class="top-label-wrapper">
                                            <?php
                                            $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                                ->init($_product, 'product_page_image_large')
                                                ->constrainOnly(FALSE)
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize(270, 371)
                                                ->getUrl();
                                            ?>
                                            <?php //check product new?>
                                            <?php $newsFromDate = $_product->getNewsFromDate();
                                            $newsToDate   = $_product->getNewsToDate();
                                            $isNew ='';
                                            if (!$newsFromDate && !$newsToDate) :
                                                $isNew = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isNew = $resolver->isScopeDateInInterval(
                                                    $_product->getStore(),
                                                    $newsFromDate,
                                                    $newsToDate
                                                );
                                            endif; ?>
                                            <?php if($isNew):?>
                                                <span class="new-label"><?php echo __('New');?></span>
                                            <?php endif;?>

                                            <?php //check product special price?>
                                            <?php
                                            $specialPriceFromDate = $_product->getSpecialFromDate();
                                            $specialPriceToDate = $_product->getSpecialToDate();
                                            $isSpecial = '';
                                            if (!$specialPriceFromDate && !$specialPriceToDate) :
                                                $isSpecial = false;
                                            else:
                                                $om = \Magento\Framework\App\ObjectManager::getInstance();
                                                $resolver = $om->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                                                $isSpecial = $resolver->isScopeDateInInterval(
                                                    $_product->getStore(),
                                                    $specialPriceFromDate,
                                                    $specialPriceToDate
                                                );
                                            endif;?>
                                            <?php if($isSpecial):?>
                                                <span class="sale-label"><?php echo __('Sale');?></span>
                                            <?php endif;?>
                                        </div>
                                        <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <div class="view-product-tab"><?php echo __('View Product');?></div>
                                        </a>
                                        <div class="featured-image">
                                            <img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
                                            <div class="overlay-featured"></div>
                                        </div>
                                        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

                                        $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

                                        $addToCartUrl =  $listBlock->getAddToCartUrl($_product);?>

                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form  action="<?php echo $addToCartUrl; ?>" method="post">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="Add to Cart"
                                                        class="actions-primary">
                                                    <i class="material-icons">add</i>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <di class="stock available"><span><?php echo __('In stock') ?></span></di>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </span>
                                </span>


                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php echo $_product->getProductUrl() ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <div class="description"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');?></div>
                            <?php echo $block->getProductPrice($_product) ?>

                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
        <script type="text/javascript">
            requirejs(['jquery'],function(jQuery){
                jQuery('.category-info').click(function(){
                    jQuery(this).addClass('active');
                    jQuery('.browse-tab').removeClass('active');
                    jQuery('.category-information-section').show();
                    jQuery('.products-grid, .sidebar-main').hide();
                    jQuery('.main').addClass('full-width');
                });

                jQuery('.browse-tab').click(function(){
                    jQuery(this).addClass('active');
                    jQuery('.category-info').removeClass('active');
                    jQuery('.category-information-section').hide();
                    jQuery('.products-grid, .sidebar-main').show();
                    jQuery('.main').removeClass('full-width');
                });
            })
        </script>
    <?php }?>

    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

