<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}'>
    <label data-role="title" class="label" for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?>
            <i class="<?php echo 'arrow_'.$_option->getId()?> material-icons list-group-down keyboard-down">keyboard_arrow_down</i>
            <i class="<?php echo 'done_'.$_option->getId()?> material-icons list-group-down active done-icon" style="display:none">done</i>
        </span>
    </label>
    <div class="control" data-role="content">
        <?php echo $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>

